CREATE TABLE Users(
	ID UUID PRIMARY KEY,
	DisplayName varchar(100),
	Email varchar(100) NOT NULL UNIQUE,
	CreateDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UpdateDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
